### ISSUE TITLE
Rotated Video also Mirrored

### ISSUE THREAD

**Issue by CBerauer** [zbabac/VCT#2]
Just downloaded the latest version and found that if i rotate a video 180 degree it is not only rotated but also mirrored. This was MP4 to MP4.

**Comment by zbabac** [comment]
I just checked and found out that I used (at given time it was probably wanted option) video filter in ffmpeg:
`-vf "vflip"`
I will check this with other users and also explore option to auto rotate. That is a feature of newer versions of ffmpeg (I included rather new version). This feature works if video metadata is present. I will have to test it. You can do so as well, just remove rotation option
In meantime you could you workaround by manually changing command. I don't know exactly what is the effect, so try adn see what's the best for you. Please replace:
`-vf "vflip"`
with:
`-vf "vflip,hflip"`
or:
`-vf "rotate=PI:bilinear=0,format=yuv420p"`
or
`-vf "transpose=2,transpose=2,format=yuv420p"`
or maybe the best is to try new rotate filter:
`-vf "rotate=PI"`

**Comment by zbabac** [comment]
I built test version 1.9.3.4 in test branch. 
Please download VCT.exe from test: VCT/bin/Debug/VCT.exe and replace file in your installation folder, "C:\Program Files\VCT\VCT.exe" and check if it's ok now.

**Comment by CBerauer** [comment]
The new test version works perfectly. Thanks for the quick fix.

**Comment by zbabac** [comment]
No problem, glad to help when I find time!
